[0;33m--- WARNING: GDB cannot open serial ports accessed as COMx[0m
[0;33m--- Using \\.\COM11 instead...[0m
[0;33m--- esp-idf-monitor 1.2.1 on \\.\COM11 115200 ---[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---[0m
[0;33m0x42007cfc: light_driver_init at C:/Users/Stephen/esp/esp-idf/examples/zigbee/light_sample/HA_on_off_light/main/light_driver.c:60 (discriminator 1)
[0m
[0;33m0x40808a63: _esp_error_check_failed at C:/Users/Stephen/esp/esp-idf/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x4080062e: panic_abort at C:/Users/Stephen/esp/esp-idf/components/esp_system/panic.c:452
[0m
[0;33m0x40808a6e: __ubsan_include at C:/Users/Stephen/esp/esp-idf/components/esp_system/ubsan.c:313
[0m
[0;33m0x40800001: _vector_table at ??:?
[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\Stephen\\esp\\esp-idf\\examples\\zigbee\\light_sample\\HA_on_off_light\\build\\light_bulb.elf', '-ex', 'target remote | "C:\\Users\\Stephen\\.espressif\\python_env\\idf5.1_py3.11_env\\Scripts\\python.exe" -m "esp_idf_panic_decoder" --target esp32c6 "C:\\Users\\Stephen\\AppData\\Local\\Temp\\tmpfnvhsfkc"', '-ex', 'bt']' returned non-zero exit status 1.
b"error starting child process '| C:\\Users\\Stephen\\.espressif\\python_env\\idf5.1_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Stephen\\AppData\\Local\\Temp\\tmpfnvhsfkc': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m0x4001975a: software_reset_cpu in ROM
[0m
[0m
